/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ManagepassengerView extends javax.swing.JFrame {

    /**
     * Creates new form managepassenger
     */
    public ManagepassengerView() {
        initComponents();
        fetchAndDisplayPassengerData();
         setLocationRelativeTo(null);
    }
    
    private void fetchAndDisplayPassengerData() {
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/studentdb", "root", "");
        String sql = "SELECT * FROM managepassenger";
        PreparedStatement ptst = (PreparedStatement) con.prepareStatement(sql);
        ResultSet rs = ptst.executeQuery();
        DefaultTableModel dt = (DefaultTableModel) passengertable.getModel();
        dt.setRowCount(0); // Clear the table
        while (rs.next()) {
            Object[] row = {rs.getString("passengername"), rs.getString("gender"), rs.getString("nationality"), rs.getString("passportnumber"), rs.getString("phone")};
            dt.addRow(row);
        }
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pn = new javax.swing.JLabel();
        ph = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        passengername = new javax.swing.JTextField();
        nationality = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        passport = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        passengertable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 164, 173));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Manage passenger");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 400, 54));

        pn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        pn.setForeground(new java.awt.Color(153, 255, 204));
        pn.setText("Passengrer Name ");
        jPanel1.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 124, -1, 27));

        ph.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ph.setForeground(new java.awt.Color(153, 255, 204));
        ph.setText("Phone ");
        jPanel1.add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 124, 56, -1));

        pass.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(153, 255, 204));
        pass.setText("Passport Number");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 124, -1, -1));

        n.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        n.setForeground(new java.awt.Color(153, 255, 204));
        n.setText("Nationality");
        jPanel1.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 124, 89, -1));

        g.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        g.setForeground(new java.awt.Color(153, 255, 204));
        g.setText("Gender");
        jPanel1.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 128, 62, -1));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 169, 103, -1));
        jPanel1.add(passengername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 169, 119, -1));
        jPanel1.add(nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 169, 121, -1));
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 169, 106, -1));
        jPanel1.add(passport, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 169, 110, -1));

        insert.setBackground(new java.awt.Color(0, 102, 255));
        insert.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        insert.setText("INSERT");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel1.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 207, -1, -1));

        update.setBackground(new java.awt.Color(0, 102, 255));
        update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 207, -1, -1));

        delete.setBackground(new java.awt.Color(0, 102, 255));
        delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 207, -1, -1));

        passengertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PassengerName", "Gender", "Nationality", "PassportNumber", "Phone"
            }
        ));
        jScrollPane1.setViewportView(passengertable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 252, 610, 120));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("<BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 22, -1, -1));

        reset.setBackground(new java.awt.Color(0, 102, 255));
        reset.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 85, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image2.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 700, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
                                             
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/studentdb", "root", "");
        String sql = "INSERT INTO managepassenger (passengername, gender, nationality, passportnumber, phone) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement ptst = (PreparedStatement) con.prepareStatement(sql);
        ptst.setString(1, passengername.getText());
        ptst.setString(2, gender.getText());
        ptst.setString(3, nationality.getText());
        ptst.setString(4, passport.getText());
        ptst.setString(5, phone.getText());
        ptst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data inserted successfully!");
        con.close();
        
        // Refresh the JTable
        fetchAndDisplayPassengerData();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }


    }//GEN-LAST:event_insertActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
        // Get the input values from the text fields
        String passengername = pn.getText();
        String gender = g.getText();
        String nationality = n.getText();
        String passportnumber = pass.getText();
        String phone = ph.getText();
        
        // Load the MySQL driver and establish a connection
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/studentdb", "root", "");
        
        // Prepare the SQL update statement
        String sql = "UPDATE managepassenger SET gender=?, nationality=?, passportnumber=?, phone=? WHERE passengername=?";
        PreparedStatement ptst = (PreparedStatement) con.prepareStatement(sql);
        
        // Set the parameters for the update statement
        ptst.setString(1, gender);
        ptst.setString(2, nationality);
        ptst.setString(3, passportnumber);
        ptst.setString(4, phone);
        ptst.setString(5, passengername);
        
        // Execute the update statement
        ptst.executeUpdate();
        
        // Show a success message
        JOptionPane.showMessageDialog(this, "Record Updated!");
        
        // Close the PreparedStatement and the connection
        ptst.close();
        con.close();
        
        // Refresh the JTable to reflect the changes
        fetchAndDisplayPassengerData();
    } catch (Exception e) {
        // Show an error message in case of any issues
        JOptionPane.showMessageDialog(this, e);
        e.printStackTrace();
    }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/studentdb", "root", "");

        // Get the selected row index
        int selectedRowIndex = passengertable.getSelectedRow();
        if (selectedRowIndex != -1) {
            // Get the passenger name from the selected row
            String passengerName = passengertable.getValueAt(selectedRowIndex, 0).toString();
            
            // Prepare the DELETE SQL statement
            String sql = "DELETE FROM managepassenger WHERE passengername = ?";
            PreparedStatement ptst = (PreparedStatement) con.prepareStatement(sql);
            ptst.setString(1, passengerName);
            ptst.executeUpdate();
            
            // Remove the selected row from the JTable model
            DefaultTableModel model = (DefaultTableModel) passengertable.getModel();
            model.removeRow(selectedRowIndex);
            
            JOptionPane.showMessageDialog(this, "Data deleted successfully");
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
        }

        con.close();
        
        // Refresh the JTable
        fetchAndDisplayPassengerData();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_deleteActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard= new Dashboard();
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        passengername.setText("");
    gender.setText("");
    nationality.setText("");
    passport.setText("");
    phone.setText("");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagepassengerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagepassengerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagepassengerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagepassengerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagepassengerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JLabel g;
    private javax.swing.JTextField gender;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel n;
    private javax.swing.JTextField nationality;
    private javax.swing.JLabel pass;
    private javax.swing.JTextField passengername;
    private javax.swing.JTable passengertable;
    private javax.swing.JTextField passport;
    private javax.swing.JLabel ph;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel pn;
    private javax.swing.JButton reset;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
